ALTER TABLE crawled_pages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE crawled_pages ADD COLUMN IF NOT EXISTS readability_score FLOAT DEFAULT 0.0;
ALTER TABLE crawled_pages ADD COLUMN IF NOT EXISTS domain_score FLOAT DEFAULT 0.0;
